# Generated by Django 5.2.13 on 2026-04-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('project_type', models.CharField(choices=[('panneau', 'Panneau decoratif'), ('vitrail', 'Vitrail architectural'), ('luminaire', 'Luminaire'), ('restauration', 'Restauration'), ('autre', 'Autre')], max_length=20)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('budget', models.CharField(blank=True, choices=[('<500', 'Moins de 500 EUR'), ('500-1500', '500 a 1 500 EUR'), ('1500-5000', '1 500 a 5 000 EUR'), ('>5000', 'Plus de 5 000 EUR')], max_length=20)),
                ('description', models.TextField()),
                ('timeline', models.CharField(blank=True, max_length=200)),
                ('reference_images', models.FileField(blank=True, null=True, upload_to='quotes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
